[build]
builder = "NIXPACKS"

[phases.setup]
nixPkgs = ["python312"]

[variables]
PYTHONUNBUFFERED = "1"

[services.web]
startCommand = "gunicorn -w 2 -k gthread -t 120 -b 0.0.0.0:${PORT} Planejamento:app"
